var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   #            ",
   "                           /H                                     xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                   o o       xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                  xxxxx                           xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                         T?                     xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                  /H                                          xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                     T?               ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                          T?   x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x     #   x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x          T?                                                         ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "              /H                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x        #                    ",
   "              /H              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                            xxx xxx  xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                            x xxx x  x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                            x              x   xxxxxxxxxxxxxxxxxxxxxxx                           T?           ",
   "                            xx            xx                                         xxx                      ",
   "  xxx                        x     xx     x                                         x!!!x                xxx  ",
   "  x x         /H             x    xxxx    x                                          xxx                 x x  ",
   "  x                          x    xxxx    xxxxxxx                        xxxxx                             x  ",
   "  x                          x            x                              x   x                             x  ",
   "  x                          xx           x                        T?    x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                          ",
   "                                                                                                          ",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "               x                |       |          |           |        |          v    x                 ",
   "               x                                                                        x                 ",
   "               x                        o   o   o   o   o   o                           x                 ",
   "               x                                                                        x                 ",
   "   xxxxxxxxxxxxx /H                                                                     xxxxxxxxxxxxxx    ",
   "   x     v                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 v     x    ",
   "   x                      x                                                  x                       x    ",
   "   x                      x                        x                     T?  x                       x    ",
   "   x                   xxxx                        o                         xxx      o              x    ",
   "   x                   xxxx                  x          x                    xxxxx                 xxx    ",
   "   x        xxxxxxxxxxxxxxx /H                     x                         xxxxxxxxxxxxxx          x    ",
   "   x           x                         x   o     x    o     x                           x          x    ",
   "   xxx                                                                                  o xxxx  o    x    ",
   "   x                                                                   o                  x          x    ",
   "   x                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxx          x    ",
   "   x        x                                                                             x       xxxx    ",
   "   x        x                                                                             x          x    ",
   "   x       xxxxx                                   #        xxxx                        T?x          x    ",
   "   x           xxxxxxxxxxxx       xxxx           xxxx                        xxxxxxxxxxxxxxxxx       x    ",
   "   xxx                    x                                           o      x     |                 x    ",
   "   x                      x            xxxx                          xxxxx   x                     xxx    ",
   "   x                      x                                                  x                       x    ",
   "   x  @                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                       x    ",
   "   xxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxx    ",
   "               x /H                        x                           x                x                 ",
   "               x                    o               o              o                    x                 ",
   "               x                                    x                                 xxx                 ",
   "               x         =                          x                         =      xxxx                 ",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
   "                                                                                                          ",
   "                                                                                                          "],
  ["           v                     |          |               v         ",
   "                                                                      ",
   "                                                                      ",
   "                      x                                            T? ",
   "        o        x          o                                         ",
   "        x                  xx                              o o        ",
   "        x                            x                   xxxxxxx      ",
   "        x               x      x          x          xx        x      ",
   "        xxxxxxx                      o         xxx             xx     ",
   "     /H           o                 xx           T?                   ",
   "                  xxxx                  x   #                        x",
   "                     xxxx         o         x         o             xx",
   "               |           x     xxx                  x               ",
   "               x                   x                     x            ",
   " @       x     |               xx  xxx                   xxxx      o  ",
   "xxxxx                      xxxxxx                                xxxxx",
   "    x       x      xxxxxxx                o              T?      x    ",
   "    x!xxx!!!!!!!!!!!!!!!x!!!!!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!x    ",
   "    x!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    ",
   "    x!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!x    ",
   "    x!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!!!!!!!!!x    ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "                                                                      ",
   "                                                                      "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                       /H                                                    o o oxxx x       ",
   "                   xxx                                                                              # x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                     T?                                       ",
   "                                        T?            xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                         T?   ",
   "                          o                T?                                   x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                   T?      ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                            v            ",
   "                                                                                                         ",
   "                                                                                                         ",
   "                                                                                                         ",
   "        /H                                     xxxxx                                  o                T?",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "               x                                                              v    x                     ",
   "      xx       x  o                                                                x                     ",
   "               x            =                             =              x         x                     ",
   "            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxx                     ",
   "                                                                         x         x                     ",
   "                                                                 o       x         x                     ",
   "      xx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxx      xxx       x                     ",
   "                    x                                    x!!!!!!!!!!!!!!!x         x                     ",
   "              xxxxxxx   o  o  o                          xxxxxxxxxxxxxxxxx         x                   T?",
   "       xx           x                                                            xxx                     ",
   "                    x                     =      x                                 x                     ",
   "                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x                     ",
   "           xx                                             |         |    x         x                     ",
   "                                                                       o x         x        o            ",
   "                               xxxxxxxxxxxxxxxxx                         x       xxx       xxx           ",
   "                               x      #        x                       o x         x                     ",
   "                xxxxxxxxxxxxxxxx               xxxxxxxxxxxxxxxxxxxxxxxxxxxxx       x           xxx       ",
   "                   x                                                               x                     ",
   "                   x                                                             xxx              xxx    ",
   "         xx        x                                                               x                     ",
   "                   x                            =               =                  x                     ",
   "                   x                                                       xxx     x                     ",
   "                   x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  xxx",
   "xxx         xxxxxxxx           x                                                                      x  ",
   "  x                            x o                                                                   xx  ",
   "  x                        xxxxx                                                                    xxx  ",
   "  x   @                    xxxxx                                  xx                          T?    xxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
